common:
    lid_topic:  "/rslidar_points"
    imu_topic:  "/imu/data"
    time_sync_en: true
    
preprocess:
    lidar_type: 4                # 4 for C16 Leishen Lidar
    scan_line: 16
    blind: 4
    time_scale: 1e-3

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     150.0
    extrinsic_est_en:  true
    extrinsic_T: [ 0.075, 0.0, 0.023 ]
    extrinsic_R: [0, -1, 0,
                  1, 0, 0,
                  0, 0, 1]

publish:
    path_publish_en:  false       # 不发布路径，节省资源
    scan_publish_en:  true        # 发布点云用于避障
    scan_effect_pub_en: false
    dense_publish_en: false
    scan_bodyframe_pub_en: true
    tf_imu_frame: "body"          # Fast-LIO TF child frame
    tf_world_frame: "camera_init" # Fast-LIO TF parent frame

# 关闭轨迹保存
path_save_en: false

# 关闭 PCD 保存（不建图）
pcd_save:
    pcd_save_en: false
    interval: -1

feature_extract_enable: false
point_filter_num: 3
max_iteration: 3
filter_size_surf: 0.5
filter_size_map: 0.5
cube_side_length: 1000

ivox_grid_resolution: 0.5
ivox_nearby_type: 18
esti_plane_threshold: 0.1
